### ISSUE TITLE
Great tool! Why is the time not set to Zürich time?

### ISSUE THREAD

**Issue by zdavatz** [golonzovsky/vacme-zurich-parser#1]
1. Thank you for the great tool!
2. Why is the time not set to Zürich time?
3. `{"last_refresh":"Mon, 10 May 2021 13:20:25 GMT","locations":[],"refresh_interval_sec":600,"source":"https://github.com/golonzovsky/vacme-zurich-parser","vaccination_group":"N"}`

**Comment by golonzovsky** [comment]
hey! 
1. thanks ;) 
2. I will change all times to millis, so it will be easier to use in UIs and programmatically
3. Exactly, currently available locations pop-up from time to time, but not often.

API is moved to `https://vacme.kloud.top/api`, and new format with millis is deployed:
 ![Screenshot from 2021-05-10 20-44-34](https://user-images.githubusercontent.com/2477950/117708826-8d7c9c80-b1d0-11eb-87ff-bae191573c9b.png)

I'm adding simple UI as well, hope you'll like it (https://vacme.kloud.top). 

![Screenshot from 2021-05-10 20-43-03](https://user-images.githubusercontent.com/2477950/117708658-602fee80-b1d0-11eb-9e38-cc42a6ea7e7a.png)

**Comment by zdavatz** [comment]
Very nice, thank you @golonzovsky! Now if you can make those `Impfzentrum` Links clickable then it would be perfect.
