### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by deuxnids** [golonzovsky/vacme-zurich-parser#7]
Hi @golonzovsky,

I was doing quite the same parsing for be.vacme.ch. So nice that you shared your code! Thanks. 

Currently I have some issues with the authentication. Sometimes I get a 403 forbidden error. Did you also notice it? How did you solve it?

Thanks for your help. Cheers from Bern

**Comment by golonzovsky** [comment]
Hey @deuxnids, great you found this useful! 

Usually invalid token gives 401. 403 might mean you are scraping to often. As far as I understand they use this FortiADC WAF, which might trigger rate limiting. I got my IP blocked once when my service was misbehaving - had to switch IP and I think it was 403. But this is just my guess.

Try to log 403 response body (often content type is `text/html`) or open in browser from affected IP. They usually describe cause better. Let me know if you have more info on that!   

(I will try to add Bern as well, once I stabilize current version a bit.)

**Comment by golonzovsky** [comment]
got few more cases of `403 Forbidden` - for me usually means my IP got blocked by their WAF, and I need to rotate to the new one. 

Last case for me was when they added filtering to the list, and my code was still trying to scrape `noFreieTermine` ones. This requests were considered 'suspocious' and my IP got blocked. 

Feel free to reopen/comment if you have new info

**Comment by golonzovsky** [comment]
update: I had recently lots of 401 and 403s with IPs blocked. I ended up adding delay 1s between each request and it improved stability by a lot. https://github.com/golonzovsky/vacme-zurich-parser/commit/9971a71e54cc563df9b30ef4a38761f6f0b048fc

I was able to make scraping more often (once per 3 min) now, and still have no issues with being blocked. Hope this helps, cheers

**Comment by deuxnids** [comment]
Thanks @golonzovsky. Let me know If I can help you ( to the best of my ability) for be.vacme.
