### ISSUE TITLE
Parser can now be simplified as the Drop-Down has improved

### ISSUE THREAD

**Issue by zdavatz** [golonzovsky/vacme-zurich-parser#8]
1. The drop-down now separates between `Keine Termine` and `Termine`
2. ![termine](https://user-images.githubusercontent.com/4953/118113330-70b9b200-b3e6-11eb-9699-59ddc8a7ad62.png)

**Comment by golonzovsky** [comment]
Thanks for heads up! Added pre-filter on `noFreieTermine` field. 
https://github.com/golonzovsky/vacme-zurich-parser/commit/8bee2161d94ca954a0cdbc42e92f8d5340ee9f8c

Originally this broke parser, as requesting location with this fiield set to False was returning 403, captchas, and blocked my  another IP eventually. 

Unfortunately if location is in dropdown - it still can be without slots :( Seems this 2 parts are not in-sync on their side. 

But this is definitely a step in right direction!

**Comment by zdavatz** [comment]
Yeah, the two parts are not in Sync! It is a half-a** solution ;).
